# install and import numpy
!pip install numpy


In [2]:
import numpy as np

**The Basics**

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.array([
    [1,2,3],
    [4,5,6]
])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# get shape
print(b.shape)
print(a.shape)

(2, 3)
(3,)


In [36]:
# get dimention
#b.ndim
print(b.ndim)

2


In [40]:
# get type
# a.dtype
print(a.dtype)


int64


In [47]:
# get size
print(a.itemsize)
print(b.itemsize)

8
8


In [48]:
# total size
print(a.size)
print(b.size)

3
6


**Multi Dimentional Array**

In [7]:
thd_a = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

print(thd_a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# shape of this array
print(thd_a.shape) #(num of matrix, num of rows(rach matrix), num of columns(each row))

(2, 2, 3)


**Traverse Multi-d Array**

In [12]:
thd_a = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
print(thd_a[0,0,0]) # this method is faster
print(thd_a[0][0][0]) # both are correct

print(thd_a[0,1,0]) # so on...


1
1
4


**String Concatenation**

In [15]:
array = np.array(
    [
        [
            ['A','B','C'],
            ['D','E','F'],
            ['G','H','I']
        ],
        [
            ['J','K','L'],
            ['M','N','O'],
            ['P','Q','R']
        ],
        [
            ['S','T','U'],
            ['V','W','X'],
            ['Y','Z',' ']
        ]
    ]
)
word = array[0,0,0] + array[0,0,1] + array[0,2,2] + array[0,1,0]
print(word)

my_name = array[2,2,0] + array[0,0,0] + array[0,2,1] + array[0,2,2] + array[2,2,0] + array[0,0,0]
print(f"My name is {my_name}")



ABID
My name is YAHIYA


# slicing

**2D Array**

In [ ]:
two_d = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]
                ])
print(two_d[0]) # 1st row
print(two_d[1]) # 2nd row

print(two_d[-1]) # last row

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
# print(two_d[start : end : step , start : end : step])
# ----> here two_d[row index , column index]

print(two_d[0:2]) # 0,1 row
print()
print(two_d[:, 0:2]) # 0,1 column
print(two_d[::, 0:2]) # 0,1 column
print()
print(two_d[0,0]) # 0,0 element

[[1 2 3]
 [4 5 6]]

[[1 2]
 [4 5]
 [7 8]]
[[1 2]
 [4 5]
 [7 8]]

1


In [ ]:
two_d = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]
                ])

print(two_d[:,-1]) # last column
print(two_d[::-1,::-1]) # reverse


[3 6 9]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [39]:
array = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(array[0:2, 0:2])
print()
print(array[1:3, 1:3])

[[1 2]
 [5 6]]

[[ 6  7]
 [10 11]]


# we can specify the data type of the array

In [50]:
a = np.array([
    [1,2,3],
    [4,5,6]
    ] , dtype = 'int32')
print(a)

[[1 2 3]
 [4 5 6]]
