**simple arithmatic operations**

In [1]:
# import numpy as np
import numpy as np

In [2]:
arr = np.array([1,2,3])
print(arr + 1)
print(arr * 2)
print(arr - 3)
print(arr / 4)
print(arr ** 2)
print(arr % 2)


[2 3 4]
[2 4 6]
[-2 -1  0]
[0.25 0.5  0.75]
[1 4 9]
[1 0 1]


**Vectorized Operation**

In [3]:
arr = np.array ([1.2, 2.3, 3.1, 4.2])
print(np.sqrt(arr))

print(np.round(arr))

[1.09544512 1.51657509 1.76068169 2.04939015]
[1. 2. 3. 4.]


**Excerise**

In [4]:
import numpy as np
radius = np.array ([1,2,3,4])
area = np.pi * radius ** 2
print(area)

[ 3.14159265 12.56637061 28.27433388 50.26548246]


**Elementwise Operation**

In [5]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [6]:
print(arr1 // arr2) #Floor Division
print(arr1 % arr2) 
print(arr1 ** arr2) 
print()
print(arr1 @ arr2) #Dot Product
print(arr1.dot(arr2)) #Dot Product

[0 0 0]
[1 2 3]
[  1  32 729]

32
32


**Comparison Operators**

In [7]:
marks = np.array([70,55,60, 90, 34, 80])
print(marks >= 80)
print(marks == 90)
print(marks != 80)

[False False False  True False  True]
[False False False  True False False]
[ True  True  True  True  True False]


**Broadcasting**

In [8]:
# Rule 1 : 

In [9]:
# scalar + array
a = np.array([1,2,3])
b = 5

print(a+b)

[6 7 8]


In [ ]:
# 1D + 2D

a = np.array([
    [1,2,3],
    [4,5,6]
])
b = np.array([10, 20 ,30])

print(a.shape)
print(b.shape) # (3,) is considered as (1,3)

print()
print(a+b)        # array b considered as : b =( [ 10, 20 , 30 ]
                #                              [ 10, 20 , 30]  )

(2, 3)
(3,)

[[11 22 33]
 [14 25 36]]


In [20]:
#column vector + row vector
x = np.array([
    [1],
    [2],            # shape (3,1)
    [3]
])

y = np.array([10, 20, 30])  # shape (3,) considered as (1,3)

"""
x considered as : 
x = [
    [1, 1, 1],
    [2, 2, 2],          
    [3, 3, 3]
]

y considered  as : 
y =[
    [10, 20 ,30],
    [10, 20, 30],
    [10, 20, 30]
]
"""

print(x+y)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
# different dimention
a = np.array([1, 2, 3]) # a is : (3,) considered as (1,3)

b = np.array([      # b is (2,1)
    [10],
    [20]
])
"""
[1,2,3]
[1,2,3]
[1,2,3]

    +
[10, 10, 10]
[20, 20, 20]

"""
print(a+b)

[[11 12 13]
 [21 22 23]]


**Aggregate Function**

In [7]:
import numpy as np

arr = np.array( [
    [2, 1, 3, 4],
    [5, 6, 7, 8]
] )

print(np.sum(arr)) # sum of all elements
print(np.sum(arr, axis=0)) # sum of each column
print(np.sum(arr, axis=1)) # sum of each row

36
[ 7  7 10 12]
[10 26]


In [8]:
print(np.mean(arr)) # average
print(np.median(arr)) # median
print(np.std(arr)) # standard deviation
print(np.var(arr)) # variance

4.5
4.5
2.29128784747792
5.25


In [9]:
print(np.min(arr)) #min value
print(np.max(arr)) #max value

1
8


In [10]:
print(np.argmin(arr)) # index of min value 
print(np.argmax(arr)) # index of max value

1
7


In [ ]:
import numpy as np

arr = np.array( [
    [2, 1, 3, 4],
    [5, 6, 7, 8]
] )

print(np.sum(arr, axis=1)) # sum of all rows
print(np.sum(arr, axis=0)) # sum of all columns

[ 7  7 10 12]
[10 26]


**Filtering**

In [ ]:
import numpy as np

ages = np.array([12, 15, 17, 20, 22, 25, 27, 29, 32, 35, 37, 40, 42, 45, 47, 50, 52, 55, 57, 60])

teenage = ages[ages < 18]           # boolean indexing
adult = ages[(ages >= 18) & (ages < 40)]   # in numpy & is used for and, its like C/C++

print("Teenage:", teenage)
print("Adult:", adult)




Teenage: [12 15 17]
Adult: [20 22 25 27 29 32 35 37]


In [ ]:
# odd even using boolean indexing
num = np.array([1,2,3,4,5,6,7,8,9,10])
odd = num[num%2==1]
even = num[num%2==0]

print(odd)
print(even)

[1 3 5 7 9]
[ 2  4  6  8 10]
[ 2  4  6  8 10]


In [ ]:
# in boolean indexing shaoe of original array is changed
# for example : 
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

even = arr[arr % 2 == 0]
print(even) 

# 2D array convert to 1D array

[2 4 6 8]


In [ ]:
"""
The `where()` function allows preserving the shape of the original array
while replacing values based on specified conditions.

but boolean indexing have less time complexity.
"""

In [ ]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
even = np.where(arr%2==0, arr, -1)
print(even)

[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]
