**Random Number**

In [53]:
import numpy as np

rn = np.random.default_rng()
print(rn.integers(1,10,3)) # integer function also can be written as integer(low=1, high=10, size=3)
print()
print(rn.integers(1,10,(2,2))) # random 2D array


[4 9 6]

[[5 5]
 [6 3]]


In [58]:
# using uniform method

import numpy as np;
print(np.random.uniform()) # random between 0 and 1
print(np.random.uniform(1,10)) # random between 1 and 10
print(np.random.uniform(1,10,3))
print()
print(np.random.uniform(1,10,(2,2)))

0.680740554711683
8.557879017638811
[4.96005141 5.47203709 6.82559901]

[[5.95569986 5.16257539]
 [7.86378839 5.87085595]]


In [69]:
print(np.random.uniform(-1,1))

0.5892530405399117


In [78]:
np.random.seed(1)
print(np.random.uniform(1,10)) # generate same number for specific seed

4.753198042323167


**shuffle** , **choice**

In [92]:
import numpy as np
rng = np.random.default_rng()
arr = np.array([1,2,3,4,5])
rng.shuffle(arr)
print(arr)

[5 3 1 4 2]


In [118]:
rng = np.random.default_rng()

arr = np.array(['apple', 'banana', 'orange'])

arr1 = rng.choice(arr)
print(arr1)

arr2 = rng.choice(arr, size = 2)
print(arr2)

banana
['apple' 'orange']


In [119]:
arr3 = rng.choice(arr, size = (2,2))
print(arr3)

[['banana' 'banana']
 ['orange' 'orange']]
